# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_title', models.CharField(max_length=50)),
                ('series_subtitle', models.CharField(max_length=50)),
                ('series_banner_ref', models.CharField(max_length=200)),
                ('series_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('prog_language', models.CharField(max_length=50)),
                ('yt_reference', models.CharField(max_length=200)),
                ('thumbnail_reference', models.CharField(max_length=200)),
                ('lesson_num', models.IntegerField()),
                ('post_date', models.DateField()),
                ('series_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vidseries.Series')),
            ],
        ),
    ]
