# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidseries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='site_url',
            field=models.CharField(default='127.0.0.1:8000', max_length=200),
            preserve_default=False,
        ),
    ]
